name: Create Archive

on:
  release:
    types: 
      - published

jobs:
  archive:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git*'
  
    - name: Push artifact to release
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip
